#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 27 14:19:54 2020

@author: IMAC
"""

import sqlite3
from sqlite3 import Error

def create_connection(db_file):
    #create a connection to a SQLite database
    conn=None
    try:
        conn=sqlite3.connect(db_file)
        print(sqlite3.version)
        print(6*"-"+"success"+6*"-")
    except Error as e:
        print(e)
    finally:
        if conn:
            conn.close()

if __name__=='__main__':
    create_connection(r"/Users/IMAC/desktop/python-testing-files/pythonsqlite.db")