#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 27 10:43:04 2020

@author: IMAC
"""
import csv
#from pandas import DataFrame
#C = {'Programming language': ['Python','Java', 'C++'],
 #       'Designed by': ['Guido van Rossum', 'James Gosling', 'Bjarne Stroustrup'],
 #       'Appeared': ['1991', '1995', '1985'],
  #      'Extension': ['.py', '.java', '.cpp'],
  #  }
#df = DataFrame(C, columns= ['Programming language', 'Designed by', 'Appeared', 'Extension'])
#export_csv = df.to_csv (r'/Users/IMAC/desktop/python-testing-files/lan', index = None, header=True) # here you have to write path, where result file will be stored
#print (df)


with open('/Users/IMAC/desktop/python-testing-files/demo.csv', newline='') as csvfile:
    dialect = csv.Sniffer().sniff(csvfile.read(1024))
    csvfile.seek(0)
    reader = csv.reader(csvfile, dialect)